# Generated by Django 5.0.6 on 2024-06-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bienvenida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saludo', models.CharField(max_length=300)),
                ('texto', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Encabezado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=200)),
                ('fondo', models.ImageField(blank=True, null=True, upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('servicios', models.CharField(max_length=400)),
                ('politica', models.CharField(max_length=400)),
            ],
        ),
    ]
