# Generated by Django 5.0.6 on 2024-06-21 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserva',
            new_name='Reservation',
        ),
    ]
