# Generated by Django 5.0.6 on 2024-06-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reservation_hotel_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelesCuatroEstrellas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('servicios', models.CharField(max_length=400)),
                ('politica', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='HotelesDosEstrellas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('servicios', models.CharField(max_length=400)),
                ('politica', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='HotelesTresEstrellas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('servicios', models.CharField(max_length=400)),
                ('politica', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='HotelesUnaEstrella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('direccion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('servicios', models.CharField(max_length=400)),
                ('politica', models.CharField(max_length=400)),
            ],
        ),
        migrations.RenameModel(
            old_name='Hotel',
            new_name='HotelesCincoEstrellas',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel_cinco_estrellas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.hotelescincoestrellas'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel_cuatro_estrellas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.hotelescuatroestrellas'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel_dos_estrellas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.hotelesdosestrellas'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel_tres_estrellas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.hotelestresestrellas'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hotel_una_estrella',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.hotelesunaestrella'),
        ),
    ]
